name: "aws-sam-cli"
description: "for using aws sam-cli"

branding:
  icon: "cloud"
  color: "orange"

inputs:
  cmd:
    description: "bin/bash command"
    required: true
    default: "sam --version"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.cmd }}
